version: '3.8'
services:
  # Create client container
  client: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "5173:5173" # Bind port 3000 of host to 3000 of container
    container_name: client-docker
    restart: unless-stopped
    links:
      - server
    depends_on:
      - server
  # Create backend container
  server:
    # Create backend container  
    build: ./server
    ports:
      - "8000:8000"
    container_name: server-docker
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
  # Create database container
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb-docker
    restart: unless-stopped
    volumes:
      - ./database/data:/data/db
      - ./docker-entrypoint-initdb.d/initTestData.js:/docker-entrypoint-initdb.d/initTestData.js:ro